### ISSUE TITLE
Monospace font for hypergrid

### ISSUE THREAD

**Issue by mhkeller** [finos/perspective#1008]
### Description of Problem:

When looking at data in a spreadsheet view, it can be difficult to spot aberrations in columns when the data is not in a fixed-width font. Here is an example with three digit codes, such as you find in airline data. In the current sans-serif font in the hypergrid, the trailing `I` would be very difficult to spot. Here, in monospace, it's much easier:

```
three_character_id value
AAA                10
AAAI               10
BBB                10
CCC                10
CCCI               10
```

### Potential Solutions:

It would be nice if there were a theme that used monospace for the hypergrid. I think this would be a sensible default but I would also be fine if there were just monospace variations I could easily select.

I did some experimenting and I found the most legible was this combination

```
--interface-monospace--font-family: "Inconsolata";
--hypergrid--font-size: 15px;
--hypergrid-header--font-size: 15px;
--hypergrid--font-family: "Inconsolata";
--hypergrid-header--font-family: "Inconsolata";
```

Pulling from the Google font, [Inconsolata](https://fonts.google.com/specimen/Inconsolata)

```less
@import url(https://fonts.googleapis.com/css?family=Inconsolata);
```

**Comment by sc1f** [comment]
Agreed - this is an awesome idea, and it'll help readability in the charts. I opened feature request #1006 yesterday to make chart tooltips more legible, and I think using monospace fonts is definitely the right way to go about that.

We will be deprecating `perspective-viewer-hypergrid` in the very near future, and moving onto our in-house `perspective-viewer-datagrid`, which is a lightning-fast virtualized datagrid that renders as an HTML table. This has several immediate benefits over hypergrid:

- Writing custom formatters for grid values/columns becomes extremely easy, as all elements on the grid exist in the DOM and are available through the traditional DOM API
- Styling the grid is also made far easier, as one can target the grid through styling `td` and `tr` elements, instead of using CSS variables.
- There are less rendering issues/glitches due to a more straight-forward data model that is tightly integrated with Perspective's own data model.

The datagrid plugin is available over NPM (`@finos/perspective-viewer-datagrid`) or over [CDN](https://unpkg.com/@finos/perspective-viewer-datagrid). It is under very active development and is tightly integrated with `perspective-viewer`, so using it should be as easy as including the NPM import or CDN link.

I went ahead and implemented your styling on our [`perspective-workspace` COVID Example](https://bl.ocks.org/sc1f/6a04603d60967d3356a6156cb5399884), which uses data from the New York Times and other sources to provide a workspace for analyzing COVID-19 cases in U.S. states and counties. In terms of the data grid, it uses custom styling as well as grid rendering (adding percentage signs and dollar signs into the grid), and does so in a simple way:

#### Custom Styling
```css
@import url(https://fonts.googleapis.com/css?family=Inconsolata);
td, tr {
  font-family: "Inconsolata", monospace;
  font-size: 15px !important;
}
```

#### Custom Rendering
```js
for (const viewer of document.getElementById("workspace").querySelectorAll("perspective-viewer")) {
  viewer.addEventListener("perspective-datagrid-after-update", event => {
    const datagrid = event.detail;
    for (const td of datagrid.get_tds()) {
      const metadata = datagrid.get_meta(td);
        if (metadata.column.includes("%") && typeof metadata.value === "number") {
          const pct = metadata.value.toFixed(4).toString();
          td.textContent = pct + "%";
        } else if (metadata.column === "Median Household Income (2018 Estimate)") {
            td.textContent = "$" + metadata.value;
        } else {
            td.style.display = "table-cell";
        }
      }
    });
}
```
Definitely check out `perspective-viewer-datagrid` if you can - the styling should be super easy to implement in pretty much all use cases.

**Comment by mhkeller** [comment]
Very cool thanks for the info and for going through the idea!
