### ISSUE TITLE
Source map error; error : request failed

### ISSUE THREAD

**Issue by stevedanomodolor** [finos/perspective#1013]
I am currently running perspective through through html and getting this console error concerning the material.css styling file. Please is this normal 

Source map error: Error: request failed with status 404
Resource URL: https://unpkg.com/@finos/perspective-viewer/dist/umd/material.css
Source Map URL: material.css.map

Also is it possible to plot multiple y values at the same time using for example the y line plot available

Thank you in advance

**Comment by sparsh-99** [comment]
@stevedanOgochu Can you please guide me on how to run source map file and catch error on console?

**Comment by stevedanOgochu** [comment]
I still get this as a warning. Still not sure why
`DevTools failed to load SourceMap: Could not load content for http://localhost:8080/material.css.map: HTTP error: status code 404, net::ERR_HTTP_RESPONSE_CODE_FAILURE`

**Comment by sparsh-99** [comment]
What is username and password for this host?

**Comment by stevedanOgochu** [comment]
I think I understand your first question. I am  not able to answer it
because I am not a javascript developer. I just use library for a project I
am working on.The sourcemap error I got was from a file that was belonging
to the perspective library l. The material.css is from perspective. I dont
know how to make a source map because i rarely work with javascript.

To the localhost question. The nodejs localhost server is without a
username or password.

**Comment by sparsh-99** [comment]
@stevedanOgochu Thankyou, I will look into the matter and come up with the solution as soon as possible.

**Comment by sparsh-99** [comment]
@stevedanOgochu Source map is working absolutely fine in my console without any #404 error!

**Comment by stevedanOgochu** [comment]
I have the issue when I use the material.css stylesheet. But it is more of a recommendation from the google dev tool not a major issue because the software still runs
