### ISSUE TITLE
Error activating Perspective from Mac Terminal

### ISSUE THREAD

**Issue by vidhurva** [finos/perspective#1042]
[##](url
<img width="938" alt="Screen Shot 2020-05-11 at 12 18 43 AM" src="https://user-images.githubusercontent.com/27433542/81523824-0a0a4000-931d-11ea-8062-2cd9cedac9ec.png">

) Support Question

When activating perspective from the terminal, this error appears. The error then suggests to use a @finos module instead, but the text cannot be changed. How would you implement this change to allow perspective to activate on terminal/a Windows equivalent of terminal?

**Comment by texodus** [comment]
Thanks for the report, but I think you're in the wrong place - the problem is right there in your screenshot, the error suggestion is 100% correct (you are importing the wrong module), and this screenshot did not come from Perspective's source.

I don't know what "text cannot be changed" means - this is a screenshot of your code, no?  If not, I'd recommend contacting the author of whatever it is you're using.
