### ISSUE TITLE
Table won't scroll in Firefox

### ISSUE THREAD

**Issue by cassandraqs** [finos/perspective#1125]
### Steps to Reproduce:
 1. Using the CSV example. Open in Firefox.
 2. Load a csv file that's relatively large.

### Expected Result:
Table should scroll, both horizontally and vertically.
### Actual Result:
Table won't scroll. The overflow property of regular-table is set to 'overlay' which is not valid. If I manually change it to auto, the horizontal scroll is not sufficient and some columns are still hidden.

### Environment:
firefox, tried in Ubuntu and Mac.

**Comment by texodus** [comment]
Thanks for the report!  This has been fixed in v0.5.3, however, it's worth noting that Firefox does not have exceptional scrolling performance in `regular-table` due to strange `position: fixed` behavior - you may see some visual artifacts when scrolling, in Firefox and OSX Safari (but not iOS Safari ...).

If you're having issues with v0.5.3 in a specific browser version, let us know and we can verify.

**Comment by texodus** [comment]
This has been fixed in 0.5.3
