### ISSUE TITLE
Chromium browser doesn't load perspective.wasm.worker.js in Python remote.py/remote.html example

### ISSUE THREAD

**Issue by pgagarinov** [finos/perspective#1139]
### Steps to Reproduce:
Same as in #1128 

### Actual Result:

<img width="1350" alt="image" src="https://user-images.githubusercontent.com/4868370/88724967-07f19980-d134-11ea-853e-03333a853fe9.png">

### Environment:
perspective 0.5.1

### Caveats
Same example works in Brave browser.

**Comment by pgagarinov** [comment]
Hello @texodus. I'm not sure if it is a bug or not, from reading the documentation my impression was that perspective.wasm.worker.js should be loaded from CDN when Python server is started. This is what Brave browser does: 
<img width="1218" alt="image" src="https://user-images.githubusercontent.com/4868370/88725429-c31a3280-d134-11ea-8e61-3ed8949c89e9.png">

If it is a bug is there any workaround for that? Thanks.

**Comment by texodus** [comment]
Thanks for the report, I caught this last night also.  It appears to be a regression in Chrome 84 - I've tested in 83 and it works fine.  For some reason, `__webpack_public_path__` is unset when hosted from alias un `unpkg.com`.  A work around for now is to use the direct links instead of the aliases - e.g. use [https://unpkg.com/@finos/perspective/dist/umd/perspective.js](https://unpkg.com/@finos/perspective/dist/umd/perspective.js) instead of [https://unpkg.com/@finos/perspective](https://unpkg.com/@finos/perspective)

**Comment by texodus** [comment]
Fix has been released in 0.5.3
