### ISSUE TITLE
JS Expanded Schema Definition

### ISSUE THREAD

**Issue by TimeWanderer** [finos/perspective#1190]
## Feature Request
Include native arrow types in JS schema definition as an option.

### Description of Problem:
I could not decide whether this is a bug, or it is intentional/out of inevitability but here is the problem:

When we start a table with a schema and update the table with arrow types, there can be type mismatches as JS types are more simplistic than Arrow types. To my knowledge, the 'number' type defaults to int32, but when we update it with an arrow type of UInt64, perspective complains about a type mismatch.

This problem also relates to  #1189 as this feature helps us circumvent it for the time being.

### Potential Solutions:
Including native arrow types in the schema parameters would solve this issue.

**Comment by texodus** [comment]
Thanks for the report!  This is a good catch.  The short answer is, Perspective currently doesn't officially support Arrow updates to schema-created `Table()` - you should just create your `Table()` directly from your dataset as in `worker.Table(arrow)`.

Arrow and Pandas' `DataFrame` are the only input data formats Perspective can currently read which are column-typed and come with a schema;  due to the latter, I figured the use case for explicitly re-declaring this schema for a new, empty Perspective `Table` would be fairly rare.  Internally, we do have an array of integer and float types for columns, unsigned and bitwidth variants.  When the engine was ported to WebAssembly, we discarded most numeric types that were not natively supported in Javascript, the reasoning being that this level of specificity was overkill in a language that effectively only implemented Double.  However, when reading an Arrow, we still use these more specific types for the internal Perspective `Table()`, both to preserve memory and optimize read performance, even though Perspective `table.schema()` still just reports simple family types `"integer"` and `"float"`.

There are a _lot_ of design issues to consider around this unfortunately, especially wrt `.update()` with heterogenous formats.  We've discussed exposing the full range of "internal" Perspective types to the public API, and letting `"integer"` and `"float"` continue to be aliases for `"int32"` and `"float64"` (respectively), which would make declaring a schema for Apache Arrow possible, but there would still be issues as ultimately Perspective, Arrow and `DataFrame` support slightly different type sets (eg #1189).

**Comment by TimeWanderer** [comment]
> There are a lot of design issues to consider around this unfortunately, especially wrt .update() with heterogenous formats.

I believed this was the case. I just wanted to confirm. We also use the suggested workaround. Do these limitations also make it impossible to fix #1189 ? That problem seems to be not just demoting the data type, but interpreting date type from arrow wrong. So it seems fixable.
