### ISSUE TITLE
Typescript no longer being linted 

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#1295]

**Comment by texodus** [comment]
> [Typescript was never being linted](https://github.com/finos/perspective/commit/abb5d59add17722c1a2f8acecc1ec01e17e1faa2#diff-7ae45ad102eab3b6d7e7896acd08c427a9b25b346470d7bc6507b6481575d519R98)

^ fixed title.  I vaguely recall we decided to leave this disabled due to buggy eslint integration?  Or perhaps I am slandering an innocent Open Source project, I've lost my notes from the _before times_ so it's hard to verify - either way, I am happy to have this enabled if it works and is unobtrusive.

**Comment by timkpaine** [comment]
tslint was deprecated in the somewhat recent past in favor of eslint. You put an `eslintrc` into the typescript folder at some point [here](https://github.com/finos/perspective/blob/master/packages/perspective-jupyterlab/src/ts/.eslintrc.json), but we never actually hooked it in it looks like. Regardless, its easy to hook in now that its all eslint and i've done so in #1294

**Comment by texodus** [comment]
I don't see `tslint` in `git log` - but if I'm wrong, just revert the commit that deprecated `tslint`?
