### ISSUE TITLE
JupyterLab Renderer broken on 0.6.0

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#1296]
https://github.com/finos/perspective/pull/1231#discussion_r559796431

**Comment by texodus** [comment]
I'm not familiar with the planning behind how this API matches the Python classes, but this functionality has been removed from `<perspective-viewer>` which now only supports the `load()` method (as described in #1231).  I would think this should also be removed from`@finos/perspective-jupyterlab`, as well as ultimately from the Python `PerspectiveViewer` API.  Because there's no repro or explanation, I'm not sure what is calling `update()` on the uninitialized TypeScript `PerspectiveViewer`, whether this is just how the Python `PerspectiveViewer` code wraps it's constructor initializer, etc..  

I understand you've encountered a bug but this Issue is not useful for tracking or planning.  Since the tests pass and the `/examples` I have seem to work, I'm closing it for now.  If you have a fix in mind and just want to call out that it is broken, just open a PR and save the indignity for the PR description;  or a Draft PR if you just have a failing test case.  If you want other developers to help, or to just track and document the problem for later, please open a new Issue with at least some details, so we can collaborate and ultimately fix it.

**Comment by timkpaine** [comment]
Its pretty clear, we call `viewer.update` [here](https://github.com/finos/perspective/blob/master/packages/perspective-jupyterlab/src/ts/renderer.ts#L50) and [here](https://github.com/finos/perspective/blob/master/packages/perspective-jupyterlab/src/ts/renderer.ts#L56). That hits [this line](https://github.com/finos/perspective/blob/master/packages/perspective-jupyterlab/src/ts/psp_widget.ts#L154), but viewer has no default table so `this.viewer.table` is undefined since `document.createElement("perspective-viewer")` doesn't create a table. That triggers the error `TypeError: this.viewer.table is undefined`. 

I don't think theres tests around this, but the usual examples were not run as they include loading up a csv or json as [demoed in the original PR](https://github.com/finos/perspective/pull/832#issuecomment-561933050).  Regardless, it is fixed on #1294 which guards the `PerspectiveWidget` to create a client table if `this.viewer.table` is undefined.
