### ISSUE TITLE
12AM parsed as 12PM in US-format date string

### ISSUE THREAD

**Issue by sc1f** [finos/perspective#1312]
In `strptime` as compiled for Emscripten, when given the US locale string format ("%m/%d/%Y, %I:%M:%S %p"), it incorrectly parses "12:00:00 AM" as "12:00:00 PM". In order to fix this, we will need a custom-written string parser similar to the `CustomISO8601Parser` from [arrow_csv.cpp](https://github.com/finos/perspective/blob/master/cpp/perspective/src/cpp/arrow_csv.cpp#L82).  This parser uses the `arrow::TimestampParser` interface from Apache Arrow, and should be relatively easy to write and test out. A custom parser is required because the current issue manifests itself inside a call to `strptime` (especially strange, I know), and not due to any custom code.

One can reproduce the issue by adding this block of code to `make_table` inside `emscripten.cpp` (where it is guaranteed to run as part of Perspective's Table constructor):
 
```c++
        std::tm res;
        char* ret = strptime("3/1/2020, 12:30:55 AM", "%m/%d/%Y, %I:%M:%S %p", &res);
        if (ret != NULLPTR) {
            // parses to 2020/3/1 12:30:55, which is incorrect
            // should parse to 2020/3/1 00:30:55
            std::cout << "parsed using strptime: " << res.tm_year + 1900 << "/" << res.tm_mon + 1 << "/" << res.tm_mday << " " << res.tm_hour << ":" << res.tm_min << ":" << res.tm_sec << std::endl;
        }
```

Adding this same block of code in `make_table` in `python/table.cpp` generates the correct output. Tests to reproduce this issue are in #1310 - although more tests should be added to make sure no other edge cases are created.

**For users, the best way to pass in datetime values is through `new Date()`** - date strings will always be parsed as UTC.

**Comment by pawan521** [comment]
Can i work on this??

**Comment by texodus** [comment]
@pawan521 You don't have to ask for permission, just take a crack at it and reply in this Issue have any questions.  No task marked `good first issue` should really merit exclusivity, these are small tasks that won't suffer from potentially duplicate work - learning how Perspective works is worth the time anyway!

**Comment by mahiijainn** [comment]
you can indeed create a custom string parser using the arrow::TimestampParser interface from Apache Arrow. This custom parser will ensure that the time is correctly interpreted as "00:00:00 AM" instead of "12:00:00 PM."

Here's an implementation of the custom parser based on arrow::TimestampParser:


#include <iostream>
#include <arrow/api.h>
#include <arrow/util/value_parsing.h>

Result<TimestampParser::Impl*> GetCustomTimestampParser(const string& format) {
    shared_ptr<arrow::TimestampParser> parser;
    ARROW_ASSIGN_OR_RAISE(parser, TimestampParser::Make(timestamp::TimeUnit::SECOND, format, :Timezone::UTC()));
    return parser->GetParserImpl().release();
}

tm CustomParseTime(const char* data, size_t length, arrow::TimestampParser::Impl* parser) {
  tm result{};
   Status status = parser->Parse(data, length, &result);
    if (!status.ok()) {
        cerr << "Failed to parse time: " << status.message() << endl;
    }
    return result;
}
This code sets up a custom timestamp parser with the given format and then uses it to correctly parse the time string "3/1/2020, 12:30:55 AM" into "2020/3/1 00:30:55".

You can replace the format string in the main function with your desired format ("%m/%d/%Y, %I:%M:%S %p"), and it should parse the time correctly.

**Comment by trottiemcqueen** [comment]
I will take a crack at this
