### ISSUE TITLE
Perspective-viewer compilation error due to missing loader.

### ISSUE THREAD

**Issue by tielushko** [finos/perspective#1497]
### Steps to Reproduce:
 1. Create a sample react application with: npx create-react-app perspective-sample
 2. Refer to JS User Guide and run npm i @finos/perspective-viewer @finos/perspective-viewer-d3fc @finos/perspective-viewer-datagrid @finos/perspective-webpack-plugin
 3. Create webpack.config file in the root of the project directory with the plugin usage as in docs.
 `const PerspectivePlugin = require("@finos/perspective-webpack-plugin");

module.exports = {
    entry: "./in.js",
    output: {
        filename: "out.js",
        path: "build"
    },
    plugins: [new PerspectivePlugin()]
};`

### Expected Result:
React application loading the npm perspective modules.

### Actual Result:
![image](https://user-images.githubusercontent.com/46033508/127516880-e427b3fe-ca46-4ddf-83a0-23d880a6d19d.png)

### Environment:
![image](https://user-images.githubusercontent.com/46033508/127516987-e82dba84-3a3e-43cb-8578-2ea9af0172ba.png)

### Additional Context:
used react example to refer to the source code for setting up the table. Only thing is I used JS.

**Comment by tielushko** [comment]
Is it possible to get any help with this matter? I would greatly appreciate this.

**Comment by zemeolotu** [comment]
@tielushko Take a look at this react/typescript [example](https://github.com/zemeolotu/perspective-react-typescript-example). 

It uses `webpack@5` and also take a look at the [webpack.config.js ](https://github.com/zemeolotu/perspective-react-typescript-example/blob/master/webpack.config.js)

**Comment by unkrich** [comment]
The above doesn't seem to help as CRA parses js files and the above does not and there seems to be some sort of compatibility problem with CRA & ESM compilation as far as I can tell.

**Comment by texodus** [comment]
@unkrich Apologies but there's very little we can do with just "it doesn't work".  Both @zemeolotu 's example and the React example in the main Perspective repo compile without error, maybe start with those and work up to a reproducible issue.

From a cursory look at `create-react-app`, they appear to still be on webpack 4 which does not support WebAssembly.

**Comment by tielushko** [comment]
I tried to specify the sort of steps, errors and configuration that I have used in order to generate the error that I am seeing with JS files. Is there a way to convert the usage of the TS webpack config to be used in JS to mitigate the loader problem? I would be happy to provide with additional details if needed, but I feel like I included everything I had at the time.

**Comment by texodus** [comment]
@tielushko Sorry, this thread seems to have split into two conversations.  I don't know anything about `create-react-app`, but as I mentioned above, `@finos/perspective-webpack-plugin` does not support `webpack` 4 (because it does not support `import.meta` or dynamic `import()`).  Assuming there is no way to use `webpack` 5 with `create-react-app`, you won't be able to use `@finos/perspective-webpack-plugin`  without adding your own loaders to handle these JS features.

You don't need the plugin to compile perspective though, the plugin just makes the resulting build smaller and faster - I just tested this with `create-react-app==4.0.3` and `perspective==1.0.0-rc.2` and it works fine.
