### ISSUE TITLE
Customise displayed value whilst maintaining original data type for sorting, filtering, etc. (_psp_repr_ & _psp_dtype_)

### ISSUE THREAD

**Issue by jonw09** [finos/perspective#1498]
## Support Question

I'm looking for a way to customise the value shown in the datagrid but maintain the underlying type in the Table so that filtering, sorting, etc. can be applied correctly to the column.

For example, if I had a column which contained prices I may wish to show a value such as `$1,000` however the underlying value should remain as `1000` to retain the ability to sort, filter, etc.

I've tried using various combinations of `_psp_repr_` and `_psp_dtype_`, however I can't seem to find a way to preserve the underlying data format at the same time as modifying the visible value on-screen. e.g.

```
class Price:
    def __init__(self, px):
        self._value = px

    def _psp_repr_(self):
        return "$%.2f" % self._value

    def _psp_dtype_(self):
        return float

    def __float__(self):
        return self._value
```

This correctly renders the string values in the grid, however if I try to apply a `>` filter to the column it's unsupported since the datatype is now a `str`.

Is this a supported setup or going to be supported in future?

**Comment by YUNGU23** [comment]
The ability to customize the displayed value while preserving the underlying data type in a datagrid is a desirable feature. However, it seems that the specific implementation you mentioned with _psp_repr_ and _psp_dtype_ is not supported in the context you provided.

To achieve the desired behavior of displaying a formatted value while maintaining the underlying data type for filtering, sorting, and other operations, you may need to explore other approaches or libraries that provide more flexible data grid customization options.

One possible approach is to separate the display value from the underlying data. Instead of modifying the data type and representation directly in the data object itself, you can consider creating a separate presentation layer or a view model that handles the formatting and display logic.

Here's a simplified example to illustrate this approach:

class Price:
    def __init__(self, px):
        self._value = px

    @property
    def display_value(self):
        return "$%.2f" % self._value

    def __float__(self):
        return self._value

# Usage example:
price = Price(1000)
print(price.display_value)  # Output: $1000.00
print(float(price))  # Output: 1000.0

**Comment by texodus** [comment]
@YUNGU23 Don't post chatbot content.

**Comment by texodus** [comment]
@jonw09 You can achieve this and much more with an expression column - no python needed:

```concat('$', string("Price"))```
