### ISSUE TITLE
Filtering using `in` operator doesn't work as expected

### ISSUE THREAD

**Issue by dhirschfeld** [finos/perspective#1520]
### Steps to Reproduce:
1. Display trade data using `PerspectiveWidget` 
2. Filter `account == 'STAN2'`, table correctly updates showing only `STAN2`
3. Filter `account == 'STAN4'`, table correctly updates showing only `STAN4`
3. Change filter to `in`, no change as `in ['STAN4']` is equivalent to `== 'STAN4'`
4.  Change to `in ['STAN4', 'STAN3']` ***No Change!*** :bug:
5. Confirm :bug: by changing to `in ['STAN5', 'STAN3']` again ***No Change*** - table still shows only `STAN4` trades.

### Actual Result:
![perspective_filter](https://user-images.githubusercontent.com/881019/130559074-b252a5fa-203c-4cf5-9b24-bd0c5253fab9.gif)

### Environment:
Running `perspective` 0.10.0 in an ubuntu linux container with `ipywidgets` 7.6.3 running in JupyterLab 3.1.6

**Comment by dhirschfeld** [comment]
Might be related to #1517?

**Comment by sc1f** [comment]
This looks like an issue with recent refactors of `perspective-viewer`, specifically the `Filter` enum in [view_config.rs](https://github.com/finos/perspective/blob/master/rust/perspective-vieux/src/rust/config/view_config.rs#L111), which fails when given a non-scalar type.

This issue will be fixed in the [new `perspective-viewer`](https://github.com/finos/perspective/pull/1488) before the next release.

As a temporary workaround, the `in` filter should work in Perspective 0.9.0. Thanks for the report!

**Comment by sc1f** [comment]
@texodus both `in` and `not in` are broken in master - both trace back to `view_config.rs` as being the issue.
