### ISSUE TITLE
Support python 3.10 on windows

### ISSUE THREAD

**Issue by shinny-yangyang** [finos/perspective#1682]
pip install perspective-python fail on windows python 3.10 env, error message: 

```
  running build_ext
  setup.py:104: DeprecationWarning: distutils Version classes are deprecated. Use packaging.version instead.
    cmake_version = LooseVersion(
  CMake Error at CMakeLists.txt:2 (project):
    Generator

      Visual Studio 15 2017

    could not find any instance of Visual Studio.
```

If I switch to python 3.9, pip install will success

**Comment by texodus** [comment]
Thanks for the report @shinny-yangyang!

We did not dist Windows wheels for Perspective's `1.0.7` perspective release due to a regression, and you do not have the needed dependencies to build Perspective from source, e.g. a C++ compiler (see [the development guide](https://perspective.finos.org/docs/md/development.html) for details).  I've added a Python `3.10` task to our buildbot in #1684 , so Perspective `1.0.8` will dist these barring another regression.

**Comment by shinny-yangyang** [comment]
Thank you texodus. perspective is a great project.

**Comment by texodus** [comment]
Looks like [`3.10` has some CI issues](https://dev.azure.com/finosfoundation/perspective/_build/results?buildId=3842&view=results) so this won't make `1.0.8`, we'll track this issue here.

**Comment by timkpaine** [comment]
Note that there is already a conda-forge build of perspective for windows on python 3.10
https://anaconda.org/conda-forge/perspective/files

**Comment by timkpaine** [comment]
https://github.com/finos/perspective/pull/2065
