### ISSUE TITLE
String field filter in server mode not work

### ISSUE THREAD

**Issue by shinny-yangyang** [finos/perspective#1690]
### Steps to Reproduce:
 1. pip install perspective-python 1.0.8 on python 3.9 x64, windows
 2. run examples/tornado-python/server.py
 3. open http://localhost:8080/server_mode.html in Chrome
 4. drag "City" field to "Where"
 5. click "value" editbox. a droplist shows   1,['Aberdeen']    2,['Abilene']  ...
 6. click first item  "1,['Aberdeen'] "

### Actual Result:
The datagrid show no records

### Expected Result:
http://localhost:8080/index.html works fine. The droplist will show "Aberdeen, Abilene, ,...". Then click any item, the datagrid will show some records.

**Comment by texodus** [comment]
@shinny-yangyang This example works fine for me, verified both a local build and `1.0.8` from pypi/npm;  though I do not have a Windows machine to test against, I cannot fathom how this would impact the result.

I'm guessing you have different versions of `perspective-python` (Python) and `perspective` (Javascript) installed - note this example uses the repo's local builds of these packages, the examples `server.py` uses the project root's `node_modules`, and the start scripts has a hardcoded `PYTHONPATH`.   The browser's devtools console should also provide more information on the error.

**Comment by texodus** [comment]
```
* open http://localhost:8080/server_mode.html in Chrome
```

Ah, this was the missing piece for me - I had no idea this file was there, was looking at `index.html` which shows the standard client/server architecture.  This server-mode regression appears to be due to a difference between how `perspective-python` and `perspective.js` emit CSV, with the former emitting the implicit `index` column (though it is not part of the request), and the latter omitting it (Related - #1666 covers the rendering of the `__ROW_PATH__` argument in javascript CSV, which is a comma-separated string in JS and a JSON-style Array apparently in Python).

We'll get this fixed for the next release - in the meantime, client/server mode (as in `index.html` in the same example) will still work, as should `perspective-python==0.10.3`.

**Comment by shinny-yangyang** [comment]
Thank you texodus 👍

**Comment by texodus** [comment]
The fix for this is in `1.1.0`

**Comment by shinny-yangyang** [comment]
I've upgraded to 1.1.0, but it's still not work. here's the websocket messages:

```
{"cmd":"view_method","name":"0.8195960139966858","method":"to_csv","args":[{}],"subscribe":false,"id":65}
{"id": 65, "data": "\"client (Group by 1)\"\n\n\"Bart\"\n\"Homer\"\n\"Marge\"\n"}

{"cmd":"view","view_name":"0.1480741105155554","table_name":"data_source_one","config":{"row_pivots":[],"column_pivots":[],"columns":["name","client","open","high","low","close"],"filter":[["client","==","\"Homer\""]],"sort":[],"expressions":[],"aggregates":{}},"id":85}
{"id": 85, "data": "0.1480741105155554"}

{"cmd":"view_method","name":"0.1480741105155554","method":"num_rows","args":[],"subscribe":false,"id":90}
{"id": 90, "data": 0}
```

maybe PR #1696 is necessary to fix this issue?

**Comment by texodus** [comment]
#1696 only fixes filter values that have `"` in them - it looks like you're trying the `tornado-streaming-python` example which does not have any `"`.

I just tried this example locally on `1.1.0` and it works for me.  It looks like you're using the `1.1.0` backend, are you sure you've also updated `@finos/perspective-viewer` to `1.1.0`?

**Comment by shinny-yangyang** [comment]
That's my mistake. I forgot upgrade perspective-viewer. Thank you texodus.
