### ISSUE TITLE
float32 dtype in dataframe is parsed incorrectly

### ISSUE THREAD

**Issue by wangkev** [finos/perspective#1717]
## Bug Report

Not sure if this is expected behavior, but was not very intuitive.
If perspective.Table has a `float` type, it only processes `float64` dtypes correctly.

### Steps to Reproduce:
```python
import numpy as np
import pandas as pd
from perspective import Table

values = [1.0, np.nan, 1.0]
df = pd.DataFrame({
    'float32': values,
    'float64': values,
}).astype({'float32': 'float32', 'float64': 'float64'})

t = Table({c: float for c in df.columns})
t.update(df)
pdf = t.view().to_df()

print('df', df)
print('pdf', pdf)
```

```python
df
    float32  float64
0      1.0      1.0
1      NaN      NaN
2      1.0      1.0
pdf
                                              float32 float64
0  2247116950146617980973935240244020099132744431...     1.0
1                                               None    None
2                                                0.0     1.0
```

### Expected Result:
Both float32 and float64 are parsed correctly.

### Actual Result:
Only float64 is parsed correctly.

### Environment:
perspective.__version__
'1.2.0'

**Comment by timkpaine** [comment]
Echoing comment here:

---

These both work:
<img width="438" alt="Screenshot 2023-04-14 at 11 24 00" src="https://user-images.githubusercontent.com/3105306/232086705-07fb807e-de41-461a-8669-be1b76417cd5.png">

The code in the issue explicitly tells the table to use `float` (which is `float64`) which leads to it parsing the array as `float64` instead of `float32`. I'm comfortable with these changes, which are more of a "help the user not make a mistake" rather than a bug fix, but they'll need tests added.
