### ISSUE TITLE
`yarn toggle_puppeteer` still supported? 

### ISSUE THREAD

**Issue by jkusa** [finos/perspective#1735]
## Support Question

According to the docs: 

>[](https://github.com/texodus)[](https://github.com/finos/perspective/blame/ba2b5d9a0fda1ba77361170f159f0f7c5d2f56c1/docs/development.md)[](https://github.com/burnhc)[](https://github.com/texodus)[](https://github.com/finos/perspective/blame/2415be2f2e661d7228ce33ff64847fb27323876f/docs/md/development.md)To toggle between local and Docker Puppeteer, run
>
> yarn toggle_puppeteer
>
> This will install a local copy of Puppeteer via `yarn` the first time it is run, if a local Puppeteer is not found.

https://github.com/finos/perspective/blame/master/docs/md/development.md#L254-L258

However #1488 removed `toggle_puppeteer.js`. Is this still valid? Should this option still be supported?

**Comment by texodus** [comment]
Thanks for the report @jkusa!

Indeed, these docs are outdated and the `toggle_puppeteer` script is vestigial.  In the past, we ran `puppeteer` tests in docker and hashed screenshots of the resulting page;  docker was necessary because otherwise small rendering differences between local development (Chromium on OSX) and CI (on Chromium Linux) would fail tests constantly.  Because puppeteer has a native component (chromium), we could not add it as a dev dependency, else our docker builds would pick up OSX chromium during tests.  

We've since done away with this practice, and now capture snippets of rendered HTML as test records instead, which are (mostly) immune to rendering differences.  Hence, `puppeteer` [is now a direct dev dependency](https://github.com/finos/perspective/blob/master/package.json#L72) and no special consideration needs to be taken.  To run Perspective's test suite for the first time, you need only invoke `yarn test`, presumably after using `yarn setup` to choose the package you've run.

There is one tricky gotcha, which is that `@finos/perspective-viewer` must have run `yarn test` at least once before `yarn test` will work on any subsequent package (as e.g. the D3FC tests depend on some build steps from the `test` task fo `perspective-viewer` currently ...).  Hence, for the first tun, its probably best to run `yarn build` and `yarn test` for all packages, before selecting the one you're interested in via `yarn setup`.
