### ISSUE TITLE
Support `to_posix()` for `datetime` and `date` types in ExprTK

### ISSUE THREAD

**Issue by shinny-yangyang** [finos/perspective#1768]
### Description of Problem:
I have a live stream dataset like this:
```
=========  =======   ========= =========  
time       symbol    broker    price
=========  =======   ========= =========  
10:00:00   symbolA   BrokerA   5302
10:00:03   symbolA   BrokerB   5310
10:00:08   symbolB   BrokerB   1240
10:00:15   symbolB   BrokerB   1244
...
=========  =======   ========= =========  
```

I need to calculate the recent 1 minute average price of each symbol&broker. My expected view should look like:

```
          BrokerA      BrokerB
SymbolA      5038         5210
SymbolB      1246         1233
```

### Potential Solutions:

In order to get this view, I think that I should set a filter "now() - time < 60" or "time > now() - 60". 
but perspective don't support "now()" in filter. 

May perspective consider support expression that return boolean type as filter condition?

**Comment by texodus** [comment]
Perspective already supports boolean expressions columns, as well as [specialized filter and edit support for them](https://github.com/finos/perspective/pull/1553).  What it doesn't support is comparing `datetime` to a `float` type with `<`, nor arithmetic via `-`.

It would be pretty easy to add an inverse to the `datetime()` function which converts a `datetime` column to a POSIX integer (`datetime()` does the opposite, converting a POSIX time to a `datetime` column).  I've changed your issue title to reflect this (so the perspective `CHANGELOG.md` does not report that boolean expressions filters were implemented when this issue is closed).
