### ISSUE TITLE
Export Jupyter Widget as picture

### ISSUE THREAD

**Issue by ccarli** [finos/perspective#1930]
## Feature Request
A perspective-widget python method to save the widget as a picture (something like widget.to_picture(path.png))

### Use-case:
In my organisation we use jupyter notebooks in jupyterlab environment to automate tasks and reports, often sending automated emails to colleagues and management with latest available data in table / charts.
I am using today persepective widgets in my python notebooks to explore and data because it's great and simple to use, but need to default back to matplotlib and styled dataframes when I want to send tables and charts in email.
I would be great if perspective offers a way to save the widgets as a picture for straightforward integration in emails.

possible duplicate to https://github.com/finos/perspective/issues/1393, html export feature request.

**Comment by ralphmensah** [comment]
Is this issue still opened?

**Comment by ralphmensah** [comment]
Is this Issue still opened @timkpaine 
@texodus

**Comment by timkpaine** [comment]
<img width="196" alt="Screenshot 2023-05-18 at 11 55 34" src="https://github.com/finos/perspective/assets/3105306/a1afef51-795a-443a-8e80-5ba7e5357ac8">

Some perspective plugins already support exports in the frontend via buttons, so this issue is really 2 fold:
- From python, access the PNG of a saved widget (this issue)
- From python, be able to export the widget into html (this is #1393)

**Comment by texodus** [comment]
Implemented in #2418.

Generating an actual PNG from python is not possible as the current iteration of the charting code is JavaScript (and heavily Chrome-centric). While we may eventually rewrite this, we no longer need to track support for the feature generally, so closing
