### ISSUE TITLE
Support JupyterLab 4

### ISSUE THREAD

**Issue by dhirschfeld** [finos/perspective#2307]
## Feature Request

I would like to be able to use `perspective` with the latest version of JupyterLab 🙏 

---

*Just opening this issue to more easily track progress...*

**Comment by dhirschfeld** [comment]
It appears this may depend on https://github.com/finos/perspective/issues/1946

**Comment by dhirschfeld** [comment]
IIUC `ipywidgets` 8.0.7 is the first version to support JupyterLab 4:
* https://github.com/jupyter-widgets/ipywidgets/releases/tag/8.0.7

**Comment by dhirschfeld** [comment]
***xref:*** https://github.com/jupyterlab/jupyterlab/issues/14590

**Comment by tomjakubowski** [comment]
I'm able to install perspective-python 2.7.1 with JupyterLab 4.0.9 and, to my surprise, things are working OK. Here's how I set it up:

```
$ conda create --name psp-jl4-test python==3.11
$ conda activate psp-jl4-test
$ pip install jupyterlab==4.0.9 perspective-python==2.7.1
$ pip list | grep -E 'jupyterlab|perspective-python'

jupyterlab                4.0.9
jupyterlab_pygments       0.3.0
jupyterlab_server         2.25.2
jupyterlab-widgets        3.0.9
perspective-python        2.7.1
$ jupyter lab
[I 2023-12-05 16:19:19.739 ServerApp] Serving notebooks from local directory: /Users/tom/perspective/lab
[I 2023-12-05 16:19:19.739 ServerApp] Jupyter Server 2.12.0 is running at:
```

Widgets and the MIME renderer (e.g. Right-click CSV, Open With, Perspective-CSV) are both working.

<img width="1622" alt="Screenshot 2023-12-05 at 4 24 29 PM" src="https://github.com/finos/perspective/assets/667901/9e9c15e2-651e-4b38-8e12-82becd20aa7e">

I did try this earlier with jupyterlab 4.0.0, and widgets were definitely broken. It's possible jupyterlab had a backwards compatibility issue that they've since resolved.

**Comment by texodus** [comment]
This also works fine for me (same versions as @tomjakubowski). `perspective-python` has no direct dependency on `jupyterlab` to upgrade (#2414 only upgrades what we test and/or what you'd get if you installed `jupyterlab` explicitly from perspective's `setup.py`).

If there's some more details about what specific versions/platforms don't work, please share and we'll test.

**Comment by dhirschfeld** [comment]
Just tested in JL4 and it does seem to work 👍
