### ISSUE TITLE
CLA Link Broken?

### ISSUE THREAD

**Issue by achesin** [finos/perspective#2590]
### Steps to Reproduce:
 1. Looking at https://github.com/finos/perspective/blob/master/CONTRIBUTING.md I followed the link for 
 2. Clicked the link in this line: "Complete your [FINOS CLA](https://finosfoundation.atlassian.net/wiki/spaces/FINOS/pages/75530375/Contribution+Compliance+Requirements#ContributionComplianceRequirements-ContributorLicenseAgreement) before opening a PR."
 3. Faulty webpage accessed

### Expected Result:
I expected to see a website with a link to the CLAs to sign.

### Actual Result:
<img width="1245" alt="Screenshot 2024-04-10 at 2 58 56 PM" src="https://github.com/finos/perspective/assets/33710232/f03c3ec0-b784-4fc4-b91c-f57ee5ae5fed">

### Environment:
Chrome Version 123.0.6312.107

**Comment by timkpaine** [comment]
@maoo @finos-admin can someone do a PR if possible

**Comment by maoo** [comment]
> @maoo @finos-admin can someone do a PR if possible

I'd suggest to use EasyCLA for Perspective, in order to streamline the process to manage individual and corporate CLAs, see https://community.finos.org/docs/governance/Software-Projects/easycla ; at the moment Perspective is the only FINOS project still using the deprecated FINOS CLA Bot.

Happy to enable EasyCLA and update docs, please let me know.

**Comment by texodus** [comment]
@maoo @mindthegab Sounds like y'all have given up on the DCO process then. Good to know.

I would rather close the project to contribution entirely, than switch to EasyCLA. Since that's functionally where we are right now, with the old CLA deleted and the DCO transition abandoned by FINOS, going to go ahead and close this issue as "won't fix"

**Comment by maoo** [comment]
> @maoo @mindthegab Sounds like y'all have given up on the DCO process then. Good to know.
> 
> I would rather close the project to contribution entirely, than switch to EasyCLA. Since that's functionally where we are right now, with the old CLA deleted and the DCO transition abandoned by FINOS, going to go ahead and close this issue as "won't fix"

We didn't give up on DCO, we've done all the due diligence needed to do the switch, and we got more requests from our members to use DCO for future contributions. I'll ping you via email, as I am not allowed discuss legal matters in a public forum.

@achesin - Thanks for submitting this issue and apologies for the confusion here; while we figure out the "CLA vs DCO" conversation, you can download, sign and send the signed [FINOS Individual CLA](https://github.com/finos/community/blob/main/website/static/governance-docs/ICLA.pdf) to secretary@finos.org and we'll make sure your PRs pass the CLA bot checks. Feel free to reach out to help@finos.org if you have any questions.
