### ISSUE TITLE
Citibike demo seems broken

### ISSUE THREAD

**Issue by naltmann** [finos/perspective#2670]
### Steps to Reproduce:

1. Open https://perspective.finos.org/blocks/citibike/index.html in browser

### Expected Result:
Map (I assume) displayed in left pane

### Actual Result:
Left pane is empty

### Environment:
Chrome 126 or Firefox on Windows

**Comment by ayush-241** [comment]
yes, there is no map displayed.

**Comment by BinaryBrain45** [comment]
I've conducted additional testing to confirm and expand on this issue. Here are my findings:

**Desktop browsers tested (on Windows 11):**
- Google Chrome version 126.0.6478.128
- Firefox Version 128.0
- Microsoft Edge Version 126.0.2592.102

**Mobile platforms tested:**
- Android 8
- Android 11

**Results:**
The issue persists across all tested environments. In every case, the left pane where the map should be displayed is empty.

This widespread occurrence across multiple browsers and operating systems suggests that the problem is likely with the demo itself rather than a browser-specific issue.

**Recommendations for further investigation:**
1. Check if the map data source is still accessible and correctly linked.
2. Review any recent changes to the demo code or dependencies that might have caused this.
3. Investigate potential server-side issues preventing the map from loading.

I'm happy to assist further if needed, such as examining the page source for JavaScript errors or checking the browser console for specific error messages.

In the meantime, it might be helpful to update the demo page or documentation to indicate that the Citibike demo is currently non-functional and under maintenance. This would inform other users that the issue is known and being addressed.

Please let me know if you need any additional information or testing.

**Comment by texodus** [comment]
Thanks for the report. The maps is just zoomed to the wrong spot, try zooming out and refocusing where you see data appear. 

The `perspective-viewer-openlayers` plugin sets its zoom level from the initial state, but does _not_ re-zooom when data updates. When this demo was written, the citibike feed ticked the entire dataset as its first tick, and the demo docused on NYC as a result. Now, it appears this feed has changed and the first tick is un-parseable, resulting in the zoom level being set elsewhere. I would like to address this by adding an explicit zoom reset button to this plugin, allowing you to correct the zoom level when the data shifts, or switch to an "auto-zoom" mode which re-runs the initialization logic on every tick. 

Apologies, but for now I'm locking this issue - it is attracting ChatGPT responses and I am tired of deleting them.

**Comment by texodus** [comment]
Fixed in #2762
