### ISSUE TITLE
Scroll functionality not working as expected

### ISSUE THREAD

**Issue by lyjeileen** [finos/perspective#2819]
### Steps to Reproduce:
1. Git clone the [sample project]( https://github.com/lyjeileen/perspective-bug )
2. Run `npm i` and `npm run local`
3. Open [http://localhost:3000](http://localhost:3000)
4. Click the `Navigate to a Different Page` button to go to the next page.
5. Attempt to scroll within the table on this new page.

I'm using react instead of pure javascript.

### Expected Result:
The table should scroll smoothly, allowing you to access all data within the table.
![Nov-12-2024 09-09-31](https://github.com/user-attachments/assets/abbd27a1-fb16-4a1f-8ce6-d61a704a45fb)

### Actual Result:
The scroll bar moves, but the table data itself does not move as expected when scrolling.
This error is shown in the console:

```
perspective-viewer.inline.js:7 Uncaught (in promise) x
    at n.wbg.__wbg_new_09b5236f2fcfe2c2 (webpack://rustic-ui/./node_modules/@finos/perspective-viewer/dist/esm/perspective-viewer.inline.js?:7:20655)
    at wasm://wasm/0095a752:wasm-function[1719]:0x1016ff
    at wasm://wasm/0095a752:wasm-function[452]:0x75f49
    at wasm://wasm/0095a752:wasm-function[583]:0x97e77
    at wasm://wasm/0095a752:wasm-function[759]:0xb4b67
    at wasm://wasm/0095a752:wasm-function[5807]:0x185028
    at Oe (webpack://rustic-ui/./node_modules/@finos/perspective-viewer/dist/esm/perspective-viewer.inline.js?:7:1144)
    at s (webpack://rustic-ui/./node_modules/@finos/perspective-viewer/dist/esm/perspective-viewer.inline.js?:7:258)
```
![actual](https://github.com/user-attachments/assets/b9c561f4-432b-4b06-89e7-02bbce751dce)

### Environment:
@finos/perspective version: 3.1.2
browser and version: Google Chrome Version 130.0.6723.70
OS: macOS Sonoma version 14.5

**Comment by texodus** [comment]
You have a two issues:
* [Perspective does not support ES5](https://github.com/lyjeileen/perspective-bug/blob/main/tsconfig.json#L4) - WebAssembly did not exist in this edition.
* [This `useEffect` hook is invoked multiple times on the same `perspective-viewer`](https://github.com/lyjeileen/perspective-bug/blob/main/src/perspectiveViz.tsx#L33) likely due to remounting. You are in effect chronologically calling `load` and `restore` interleaved without awaiting the result of the previous call. You must not call these async lifecycle methods on `<perspective-viewer>` without awaiting the previous call to complete. Duplicate #2652

**Comment by lyjeileen** [comment]
@texodus Thank you so much!
