### ISSUE TITLE
The relationship between sort and aggregate is unclear

### ISSUE THREAD

**Issue by ColinEberhardt** [finos/perspective#314]
I am trying to re-create the 'olympic medals' example from the ground-up as a way to understand how perspective work. Initially I am trying to create a view, without the associated `perspective-viewer` web component.

When trying to create a sorted view as follows:

```
  const view = table.view({
    row_pivot: ["country"],
    sort: [["gold","desc"]]
  });
```

A runtime error occurs because I have not specified an `aggregate` for the view. 

The [documentation](https://github.com/jpmorganchase/perspective/blob/master/docs/perspective.md#view-1) doesn't explain aggregate terribly well, or the relationship to sort.

When using the web component, I don't need to specify an aggregate:

```
    <perspective-viewer 
        view="x_bar"
        row-pivots='["country"]' 
        columns='["gold"]'
        sort='[["gold","desc"]]'>

    </perspective-viewer>
```

**Comment by texodus** [comment]
Thanks for the report!

This is not well documented - see [my response here](https://github.com/jpmorganchase/perspective/issues/272#issuecomment-429999649) for some additional color on the issue.

Basically - `aggregates` on `<perspective-viewer>` are the _default aggregate settings_ the viewer will choose when a user or developer selects a column, and apply to both selected and deselected columns, and the `columns` attribute describes the actual columns currently selected.  For the library however, `view()` is immutable, so there is no concept of default aggregates - deselected columns are simply not included in the view and cannot be later added, rather a new `view()` must be created.  Hence, for the library we have 1 confusingly named property `aggregate` which combines `aggregates` and `columns` into one property.

This clearly needs fixing.  My current thinking is to just mimic the perspective-viewer API completely in the library, and amend the the library's internal logic to also just choose defaults for `columns` selected which do not have aggregates specified.  Ignore `aggregates` which are included which do not have `columns` equivalents as there is nothing to do with them here.  This will also make the API for aggregates a simple `{"column name": "aggregate type"}` dictionary instead of the confusing list of aggregate/column specification it is now.

Does that sounds reasonable?

**Comment by texodus** [comment]
This behavior has changed quite significantly since this issue was filed.  Sorts can now be applied to columns which are not in the columns list, and aggregates can be supplied for them as well.
