### ISSUE TITLE
Source Documentation Improvements

### ISSUE THREAD

**Issue by timkpaine** [finos/perspective#384]
To enable developers to build and work on the code base, better documentation is necessary. As such we should explore adding annotation to the various important bits and autogen some documentation.

**Comment by texodus** [comment]
I agree with this sentiment whole-heartedly.

Since this issue was filed, we've added full auto-generated docs infrastructure in that reads and writes both Markdown and Sphinx, at great expense to my personal sanity.  As the task of actually documenting the code is ongoing & without completion criteria, I'll close this for now.
