### ISSUE TITLE
Customizing perspective-viewer-highcharts

### ISSUE THREAD

**Issue by wechka53** [finos/perspective#443]
Hi there,
I'm trying to use perspective charts with react and have some difficulties with customization.
Is there any way to override or customize highcharts config/markup?
As an example, I'd like to override highcharts tooltip but not sure that is's possible.

Thanks.

**Comment by timkpaine** [comment]
@texodus should this be closed now that d3fc is the default?

**Comment by texodus** [comment]
Yes.  While part of the `0.6.x` series plan is to make `D3FC` charts more configurably by moving them ot the light DOM and adding events and callbacks for formatting and interaction events, ultimately these charts are canned and will always but somewhat limited;  true customization by developers must be achieved via Perspective's under-documented [plugin API](https://blog.scottlogic.com/2019/04/23/perspective-plugin-api-how-to-build-a-new-plugin.html) and basically implementing the charts from scratch, by design (for now).
