### ISSUE TITLE
Using ChartJS with Perspective

### ISSUE THREAD

**Issue by Daniel-Davies** [finos/perspective#680]
Hello,

I am working on a small project that Perspective is ideal for, with the constraint that the charting library must be [ChartJS](https://www.chartjs.org/). 

I noticed there was an issue open a while ago about this [here](https://github.com/finos/perspective/issues/33) but I'm not sure if this went anywhere.

Does there exist a ChartJS plugin for perspective? If not I am happy to make my own PR. Would adding a plugin for a charting library be a difficult task to achieve?

**Comment by RandomFractals** [comment]
I'd like to see this happen too! Could be a worth addition to the **DataPreview 🈸**` data.preview.charts.plugin` vscode setting for devs: https://github.com/RandomFractals/vscode-data-preview#configuration

**Comment by texodus** [comment]
As described in the previous issue, we've decided not to pursue this direction.  In the time since the original issue was filed, we've also published the phenomenal `@finos/perspective-viewer-d3fc` plugin which wholesale replaces original charting plugin.

There is a [great article on the ScottLogic blog about how to make a perspective plugin](https://blog.scottlogic.com/2019/04/23/perspective-plugin-api-how-to-build-a-new-plugin.html), and PRs for new plugin packages are welcome.

**Comment by RandomFractals** [comment]
hah! yeah, that is a good read & I did clip it here for maps display: https://github.com/RandomFractals/vscode-data-preview/issues/7

so, I am guessing asking for an 'official' maps plugin by finos would be a moot point too?

Thx for your feedback on this!
