### ISSUE TITLE
Worker file's runtime location

### ISSUE THREAD

**Issue by stevenvachon** [finos/perspective#857]
## Support Question
I'm using the webpack plugin, which correctly copies the worker file to my bundle's output directory. My issue is that the worker file can't be found by my server (`localhost:3000`), where the console shows:
```
Uncaught SyntaxError: Unexpected token '<'
http://localhost:3000/perspective.wasm.worker.js
```

The file is actually at `http://localhost:3000/public/plugins/perspective-panel/perspective.wasm.worker.js`.

**Comment by texodus** [comment]
Try setting `publicPath` in the `output` section of your webpack config, ala the [webpack example](https://github.com/finos/perspective/blob/master/examples/webpack/webpack.config.js#L19), if you are not doing so already.  If this doesn't work, I may need some help getting a repro together - a minimal webpack config which replicates the problem would make this an easy fix.

The client code which downloads/instantiates the Web Worker looks for `perspective.wasm.worker.js` and `psp.async.wasm` files in the same [path](https://github.com/finos/perspective/blob/master/packages/perspective-webpack-plugin/src/js/psp-worker-loader.js#L80) where it was itself downloaded (`perspective.js` or `perspective-viewer.js`, or the asset into which it was compiled in your app).  This logic seems to be broken in your app for some reason.

I think in this case both 1) a better error message and 2) a user-configurable download location are warranted - I will add these imminently.   We could also use much better documentation on the plugin and its myriad of options - it actually supports inlining the entire worker and wasm payload into a single asset at the expense of load performance.

**Comment by stevenvachon** [comment]
> it actually supports inlining the entire worker and wasm payload into a single asset at the expense of load performance.

Initial load only?

**Comment by texodus** [comment]
Yes, initial load only, as in time-to-library-ready, not dataset load or processing time.  In this mode, you configure webpack and manually load the `perspective.wasm.worker.js` and `psp.async.wasm` directly, then use the undocumented `perspective.override()` method to override the default download logic.  This increases the cumulative payload size by ~500kb, takes 2-3x as long to load load the library cold, in addition to just wrecking havoc on debuggers and whatnot due to the asset size itself.

There is a similar [example in the `@finos/perspective-jupyterlab` module](https://github.com/finos/perspective/blob/master/packages/perspective-jupyterlab/src/ts/widget.ts#L17).  This version uses a internal custom loader (basically `raw-loader`+`worker-loader`, except that is utilizes this [`Blob()` trick](https://stackoverflow.com/questions/20410119/cross-domain-web-worker) for better cross domain compatibility with Chrome) which takes an `inline` argument, and `arraybuffer-loader` [here](https://github.com/finos/perspective/blob/master/packages/perspective-jupyterlab/src/config/plugin.config.js#L44) to load the WASM, then call `perspective.override()` function before instantiating a Web Worker.

This is a non-public, non-documented API, so subject to change. Also, note [this exception](https://github.com/pine/arraybuffer-loader#for-wasm-file) regarding incompatibility between Webpack 4 and Emscripten.

**Comment by stevenvachon** [comment]
> The client code which downloads/instantiates the Web Worker looks for `perspective.wasm.worker.js` and `psp.async.wasm` files in the same [path](https://github.com/finos/perspective/blob/master/packages/perspective-webpack-plugin/src/js/psp-worker-loader.js#L80) where it was itself downloaded (`perspective.js` or `perspective-viewer.js`, or the asset into which it was compiled in your app). This logic seems to be broken in your app for some reason.

My issue here is that `publicPath` is configurable from the server and my build is for a plugin which cannot be aware of that value. Is it possible for perspective to instead or optionally use `document.currentScript.src`?

> you configure webpack and manually load the `perspective.wasm.worker.js` and `psp.async.wasm` directly

Using [webpack-concat-plugin](https://npmjs.com/webpack-concat-plugin)?

**Comment by timkpaine** [comment]
you could try taking a look at [this project](https://github.com/timkpaine/crowdsource) that uses web packed psp served by a webserver

**Comment by stevenvachon** [comment]
There're a few issues with that project as an example:
* it doesn't include the worker and wasm in the bundle
* its `publicPath` is static and known because its webserver is part of the same project

My [project](https://github.com/stevenvachon/perspective-plugin) is a [grafana](https://github.com/grafana/grafana) panel plugin which is asynchronously loaded (via `import()`). The webserver is part of the parent project and is not aware of the (configurable) path in which plugins are loaded. I'm thinking of exposing a global `PLUGINS_URL` (or similar) in grafana's frontend runtime and building the plugin with [ynamic-public-path-webpack-plugin](https://npmjs.com/dynamic-public-path-webpack-plugin).

**Comment by stevenvachon** [comment]
Okay, the problem was that the default webpack config (that I was extending) had `publicPath: '/'` which derailed the relative pathing for the worker files (as it needed the webpack default value of `''`). It appears to be working and I think that solves this issue.

Thanks for the help!
