### ISSUE TITLE
Feature request: Reference data as argument for computed columns.

### ISSUE THREAD

**Issue by TimeWanderer** [finos/perspective#888]
Hello,

If we can embed a custom object of map type to computation specification object and inject it to computation function, we could do a lot of cool things with it. A simple example would be:

`{
  column: "StateString",
  type: "string",
  lookup: {
    id1: val1,
    id2: val2
  },
  func: (st, lookup) => {
    return lookup[st];
  },
  inputs: ["State"]
}`

Or for generating custom brackets based on column: 

`{
  column: "Bracket",
  type: "string",
  lookup: {
    lowCutoff: 10,
    highCutoff: 90,
  },
  func: (fq, lookup) => {
    if (fq < lookup[lowCutoff]) return "low";
    else if (fq > lookup[lowCutoff] and fq < lookup[highCutoff]) return "middle";
    return "high";
  },
  inputs: ["Frequency"]
}`

These can easily be implemented outside of table api before ingestion but this api would be much cleaner.

Thanks.

**Comment by texodus** [comment]
Thanks for the feature request!

Due to the way WebAssembly integrates with Javascript, calling functions and marshaling data across the boundary between these languages for this feature was quite costly.  As of 0.4.2, Perspective no longer supports Javascript functions to `computed_columns`, as the evaluation of these has moved to C++ entirely.

Within the next few releases, this new high-performance `computed_column` implementation will support expression editing w/incremental rendering within `<perspective-viewer>` - and at this point, your example might look a bit like this:

```javascript
const view = table.view({
    columns: ["Bracket"],
    computed: {
        Bracket: `Frequency < 10 ? "low" : Frequency > 90 ? "high" : "middle"`;
    }
});
```
