### ISSUE TITLE
I have question on updating view filters 

### ISSUE THREAD

**Issue by Madasamy26** [finos/perspective#935]
I have question on updating view filters 

`const worker1 = perspective.worker();
const worker2 = perspective.worker();

// Create a `table and `view` on `worker1`.
const table = worker1.table(data);
const view1 = table.view({ filter: [["State", "==", "Texas"]] });

// Create a table from `view` in `worker2`
const table2 = worker2.table(view);
const view2 = table2.view({ filter: [["City", "==", "Austin"]] });

//  Both `view1` and `view2` are updated.
table.update([{ State: "Texas", City: "Austin" }]);

//  Only `view1` is updated.
table.update([{ State: "Texas", City: "San Antonio" }]);`

If I want change the filter of view1, whats the efficient way to do that?.

**Comment by sc1f** [comment]
Views are immutable after creation, which means you’ll have to create a new view with the filters you want. You’ll also have to call ‘delete()’ on the old view in order to clean up memory allocated on the WebAssembly heap. Refer to the [conceptual overview](https://perspective.finos.org/docs/md/concepts.html) for more details.

What is your use case? For almost all simple use-cases you should be using perspective-viewer instead of manually managing your own views and tables.

On Feb 20, 2020, at 10:35 AM, Madasamy <notifications@github.com> wrote:

﻿

I have question on updating view filters

`const worker1 = perspective.worker();
const worker2 = perspective.worker();

// Create a table and viewonworker1`.
const table = worker1.table(data);
const view1 = table.view({ filter: [["State", "==", "Texas"]] });

// Create a table from view in worker2
const table2 = worker2.table(view);
const view2 = table2.view({ filter: [["City", "==", "Austin"]] });

// Both view1 and view2 are updated.
table.update([{ State: "Texas", City: "Austin" }]);

// Only view1 is updated.
table.update([{ State: "Texas", City: "San Antonio" }]);`

If I want change the filter of view1, whats the efficient way to do that?.

**Comment by sc1f** [comment]
Views are immutable after creation, which means you’ll have to create a new view with the filters you want. You’ll also have to call ‘delete()’ on the old view in order to clean up memory allocated on the WebAssembly heap. Refer to the [conceptual overview](https://perspective.finos.org/docs/md/concepts.html) for more details.

What is your use case? For almost all simple use-cases you should be using perspective-viewer instead of manually managing your own views and tables.

**Comment by Madasamy26** [comment]
Basically I need to remove the view from  table2 (refer above code) right?

**Comment by sc1f** [comment]
No, you'll need to create a new view on either `table` or `table2`. The example you're using is more complex than necessary to illustrate the point:

```javascript
const table = perspective.table(data);
const view = table.view(filter=[["State", "==", "Texas"]]);
view.delete(); // make sure the view gets deleted in order to clean up WASM heap
const view2 = table.view(filter=[["State", "==", "Utah"]]);
```
Once a view is deleted, it is dead and should not be referred to at all. Always create a new view whenever view parameters need to be changed. `<perspective-viewer>` will handle all of these semantics automatically.

**Comment by Madasamy26** [comment]
As your comment

```
const perspectiveViewer = documnet.getelementById("perspective")

const table = perspective.table(data);
const view = table.view(filter=[["State", "==", "Texas"]]);
view.delete(); // make sure the view gets deleted in order to clean up WASM heap
const view2 = table.view(filter=[["State", "==", "Utah"]]);
```
If I wants to render the view2 

const table2 = worker2.table(view2);

perspectiveViewer .load(table2)

Is it correct?

**Comment by Madasamy26** [comment]
I have found that view can also load into the <perspective-viewer> like below
```
perspectiveViewer .load(view2)
```

**Comment by sc1f** [comment]
If you're using PerspectiveViewer, there should be no need to create a second table with the filtered data. Simply use the UI or the [attribute API](https://perspective.finos.org/docs/obj/perspective-viewer.html#module_perspective-viewer..PerspectiveViewer+filters) to set a filter, and the viewer will handle everything in-between.

`perspectiveViewer.load(view2)` does exactly the same thing as `worker.table(view2)`. However, if you're using Perspective Viewer then none of this should be necessary - load the main table into the viewer and use the UI or attribute API.

**Comment by Madasamy26** [comment]
Use case is  need to switch between the  view dynamically

**Comment by sc1f** [comment]
You don't need to create your own views if you're already using perspective-viewer. Just `load` the data and use the Viewer UI or API to change filters, aggregates, etc.

Views are immutable and cheap to create and destruct (10-20 milliseconds)- calling `load` on `viewer` is a far more expensive operation and should only be done when the entire dataset has changed.

**Comment by Madasamy26** [comment]
No, I need to have separate feature as changing filters, aggregates in Viewer UI or API,  from the view

**Comment by sc1f** [comment]
I’m not sure what you’re asking to do. Filters, aggregates etc. cannot be “changed” without creating a new view. If you’re using the Viewer then your use case (and much more) are already covered.

**Comment by Madasamy26** [comment]
Yes Its covered, 
 
Assume that, the scenario is we need have set of predefined  view have already applied some filters,aggregators etc... that predefined  views can be chosen over the drop drop down from the outside and top of it, if the user wants to apply the filters etc ..they can ..

**Comment by sc1f** [comment]
This is a covered use case with the Viewer's [`restore`](https://perspective.finos.org/docs/obj/perspective-viewer.html#module_perspective-viewer..PerspectiveViewer+restore) method.

```javascript
const views = [
  {filters: [["State", "==", "Texas"]]},
  {aggregates: {"State": "distinct count"}, filters: [["State", "==", "Arkansas"]]}
]

viewer.restore(views[1]);
```

**Comment by Madasamy26** [comment]
I have tried that ...but the problem is ..whatever we have applied filter through 
```
viewer.restore(configs[1]);

```

that are all showing in viewer UI ..but In our case no need o visible the predefined filters in UI .

**Comment by sc1f** [comment]
There isn't a way to hide what transforms are applied in the UI - that undermines the point of having a UI.
