### ISSUE TITLE
Table initialization failed: RuntimeError: memory access out of bounds

### ISSUE THREAD

**Issue by alexeykulakov** [finos/perspective#936]
Hi,
I get the error when trying to run perspective WebSocketServer with arrow dataset of 10 millions rows and 8 columns (~500Mb). To be precise, the error occurs when call table object.

Is there some way to fix it?

Notice that:
1) 5 millions rows is Ok. 
2) server RAM - 32 Gb

**Code to reproduce**
```
const { WebSocketServer, table } = require("@finos/perspective");
const fs = require("fs");
const host = new WebSocketServer({ assets: [__dirname], port: 7080 });
const data = fs.readFileSync(__dirname + "/data10mln.arrow");
const tbl = table(data)
```
Error occurs on the last line

**error message**

> Table initialization failed: RuntimeError: memory access out of bounds
> RuntimeError: memory access out of bounds
>     at wasm-function[1971]:0x10cd59
>     at wasm-function[978]:0x3ead9
>     at wasm-function[1670]:0xa974e
>     at wasm-function[1666]:0x98fbf
>     at wasm-function[1665]:0x9846d
>     at wasm-function[1798]:0xcbb3c
>     at wasm-function[1797]:0xcb6fd
>     at wasm-function[1311]:0x68efe
>     at wasm-function[1100]:0x47457
>     at wasm-function[1101]:0x474af
> RuntimeError: memory access out of bounds
>     at wasm-function[1971]:0x10cd59
>     at wasm-function[978]:0x3ead9
>     at wasm-function[1670]:0xa974e
>     at wasm-function[1666]:0x98fbf
>     at wasm-function[1665]:0x9846d
>     at wasm-function[1798]:0xcbb3c
>     at wasm-function[1797]:0xcb6fd
>     at wasm-function[1311]:0x68efe
>     at wasm-function[1100]:0x47457
>     at wasm-function[1101]:0x474af
> 
> /home/akulakov/NAS/Working/finos-server/node_modules/@finos/perspective/dist/umd/perspective.node.js:7
> */Array.isArray||(Array.isArray=function(arg){return"[object Array]"===Object.prototype.toString.call(arg)}),__WEBPACK_AMD_DEFINE_ARRAY__=[],void 0===(__WEBPACK_AMD_DEFINE_RESULT__="function"==typeof(__WEBPACK_AMD_DEFINE_FACTORY__=function(){"use strict";var AUTO_SCRIPT_PATH,scripts,global="undefined"!=typeof self?self:"undefined"!=typeof window?window:void 0!==global?global:{},IS_WORKER=!global.document&&!!global.postMessage,IS_PAPA_WORKER=IS_WORKER&&/(\?|&)papaworker(=|&|$)/.test(global.location.search),LOADED_SYNC=!1,workers={},workerIdCounter=0,Papa={parse:function(_input,_config){var dynamicTyping=(_config=_config||{}).dynamicTyping||!1;if(isFunction(dynamicTyping)&&(_config.dynamicTypingFunction=dynamicTyping,dynamicTyping={}),_config.dynamicTyping=dynamicTyping,_config.transform=!!isFunction(_config.transform)&&_config.transform,_config.worker&&Papa.WORKERS_SUPPORTED){var w=function(){if(!Papa.WORKE
> abort(RuntimeError: memory access out of bounds). Build with -s ASSERTIONS=1 for more info.
>

**Comment by timkpaine** [comment]
@alexeykulakov isn't the default memory limit in node 512MB?

**Comment by timkpaine** [comment]
nvm its 1GB

**Comment by timkpaine** [comment]
@alexeykulakov can you try bumping how much memory is allocated to node?

**Comment by alexeykulakov** [comment]
Same error if increase the memory limit with command --max-old-space-size

`node --max-old-space-size=16384 server.js`

**Comment by alexeykulakov** [comment]
> @alexeykulakov can you try bumping how much memory is allocated to node?

I've tested rss size for different cases. 
*rss - Resident set size: Memory assigned to the process in bytes

1) dataset 1 million rows: rss = 104 558 592 bytes
2) dataset 10 millions rows: rss = 572 792 832 bytes (Runtime error)

**Comment by texodus** [comment]
Thanks for the report!

Unfortunately, as far as I am aware (or at least true as of recently), all modern browsers (and V8 runtimes such as node.js) have hard-coded WebAssembly heap allocation limits of 2gb.  This realistically translates to between 1gb-2gb because of the way emscripten allocates memory/`grow()` works, and Perspective will need some additional overhead over your Arrow size for indices, view contexts, etc.  In my testing, this (very very roughly**) translates to ~400mb Arrows being the threshold of what perspective and current WebAssembly runtimes can support.  If cropping your Arrow dataset slightly below this size relieves the error, this is almost certainly your issue.

Until such time that JS runtimes can allocate large WASM heaps, one option you have today is to try Perspective's [new Python module](https://perspective.finos.org/docs/md/python.html), which uses the exact same C++ code as the WebAssembly version, and can power the exact same `<perspective-viewer>` frontend.  Unlike the WebAssembly version however:

* No 2gb limit - allocate as much as Python allows.
* Will e.g. compute column aggregates in parallel and utilize SIMD and other non-wasm-supported instructions.
* No heap boundary (as there is in WebAssembly), so native interop is quite a bit faster (though this affects Arrow loading much less).
* More!  (*significant whitespace?!).

It may be worth at least testing this even just to verify that WebAssembly memory allocation limits are indeed the source of your issue.

For now I will close this issue though, as there is little we can actionably due beyond committing to continue to squeeze every byte from Perspective's allocation.  If you feel this error is not purely memory threshold related (and it may well not be) - please feel free to re-open with some more details about your failing dataset and we can take a close look.

** In general, it is difficult to translate row count to memory usage due to the way data is encoded in arrow/perspective - especially regarding strings.  A small dataset with long unique string columns may cause issues where a large one with short repeated strings or no strings at all will be fine.
